# Generated by Django 3.2.8 on 2022-11-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0002_rename_username_author_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=128)),
                ('project_link', models.TextField()),
                ('project_authors', models.ManyToManyField(to='authors.Author')),
            ],
        ),
    ]
