# Generated by Django 3.2.8 on 2022-11-23 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_rename_username_author_user_name'),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TODO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_text', models.TextField()),
                ('todo_data_create', models.DateField()),
                ('todo_data_update', models.DateField()),
                ('todo_authors', models.ManyToManyField(to='authors.Author')),
                ('todo_project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='notes.project')),
            ],
        ),
    ]
