# Generated by Django 3.2.8 on 2022-11-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='todo_close',
            field=models.BooleanField(default=False),
        ),
    ]
