# Generated by Django 3.2.8 on 2022-11-10 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='username',
            new_name='user_name',
        ),
    ]
